# Generated by Django 2.0.4 on 2018-04-11 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='owner',
            field=models.CharField(default='Mamun', max_length=100),
        ),
        migrations.AddField(
            model_name='album',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
