# Generated by Django 2.0.4 on 2018-04-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180416_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='images',
            field=models.FileField(upload_to=''),
        ),
    ]
