# Generated by Django 2.0.4 on 2018-04-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180418_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='images',
            field=models.CharField(max_length=250),
        ),
    ]
