# Generated by Django 2.0.4 on 2018-04-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180418_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
