# Generated by Django 2.0.4 on 2018-04-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_photo_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='height',
            field=models.IntegerField(default=250),
        ),
        migrations.AddField(
            model_name='photo',
            name='width',
            field=models.IntegerField(default=250),
        ),
    ]
