# Generated by Django 2.0.4 on 2018-04-30 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180428_0136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='Comments',
            new_name='comment',
        ),
    ]
