# Generated by Django 2.0.4 on 2018-05-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180430_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logtext', models.CharField(max_length=50)),
            ],
        ),
    ]
